// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meapnqpnjywhyzfiwqqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lYXBucXBuanl3aHl6Zml3cXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzODYzOTEsImV4cCI6MjA4NTk2MjM5MX0.Ro79Cp-uvE1ymu53MfTxs3EUwIFE7C2rE593OH-LJT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});